---

- name: Initialising
  hosts: vpn
  become: true
  tasks:
    - name: Updating instances
      apt:
        update_cache: yes
        upgrade: dist

    - name: Rebooting instances
      reboot:


- name: Installing
  hosts: vpn
  become: true
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Ensure group 'docker' exists
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add the user 'ubuntu' to the docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: true        

    - name: Rebooting instances
      reboot:


- name: Configuring Docker
  hosts: vpn
  become: true
  tasks:
    - name: Linking  IP to DuckDNS
      uri:
        url: "{{ vpn_duckdns_url }}"

    - name: Copying docker-compose.yml to server
      ansible.builtin.copy:
        src: files/docker-compose.yml
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Running Compose
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: /home/ubuntu

    - name: Waiting for peer profiles to be generated
      ansible.builtin.wait_for:
        path: /app/wireguard/config/peer2/peer2.png

    - name: Sleep for 10 seconds
      ansible.builtin.wait_for:
        timeout: 10

    - name: Retrieving peer1 profile
      ansible.builtin.fetch:
        src: /app/wireguard/peer1/peer1.png
        dest: files/
        flat: yes

    - name: Retrieving peer2 profile
      ansible.builtin.fetch:
        src: /app/wireguard/peer2/peer2.png
        dest: files/
        flat: yes